//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Add_Cart
    {
        public int CartID { get; set; }
        public string Item_Name { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual sport sport { get; set; }
    }
}
