//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportsStoreEntities : DbContext
    {
        public SportsStoreEntities()
            : base("name=SportsStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Add_Cart> Add_Cart { get; set; }
        public virtual DbSet<AdminRegisteration> AdminRegisterations { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<sport> sports { get; set; }
        public virtual DbSet<UserRegister> UserRegisters { get; set; }
    }
}
